knp_snappy:
    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 20 # In seconds
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'        
        options:
            page-size: A4

    image:
        enabled:    false
        #binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        #options:    []
