knp_paginator:
  page_range: 10                       # number of links shown in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
  default_options:
    page_name: page                 # page query parameter name
    distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
  template:
    pagination: 'partials/bootstrap_v5_pagination.html.twig'     # sliding pagination controls template
    sortable: '@KnpPaginator/Pagination/bootstrap_v5_fa_sortable_link.html.twig' # sort link template
    filtration: '@KnpPaginator/Pagination/bootstrap_v5_filtration.html.twig'  # filters template